future: true
permalink: /:title/
url: http://joyceyj.github.io
name: Joyce Yang
author: Joyce Yang
qq: yourqq
email: joyce3.yang@gmail.com

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: yourID
about: "这里是 Joyce Yang 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
